spring:
  data:
    mongodb:
      username: khoapd
      password: khoapd
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin


server:
  port: 8090

springdoc:
  api-docs:
    enabled: true
    path: /customer/v3/api-docs
  swagger-ui:
    enabled: true
